cloud:
  aws:
    region:
      static: eu-central-1
      auto: false
    credentials:
      access-key: notValidKey
      secret-key: notValidSecret
    end-point:
      uri: http://aws_sqs:9324
      queue: dlq

server:
  port: 8081

api:
  uri: http://localhost/contas/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notifications?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto:update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
