version: '3'
services:
  mysql:
    image: mysql:5.7.21
    ports:
      - '3306:3306'
    volumes:
      - ../src/test/resources/mysql/initdb.sql:/docker-entrypoint-initdb.d/init.sql
    stdin_open: true
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'notifications'

  wiremock:
    image: wiremock/wiremock
    container_name: wiremock
    volumes:
      - ../src/test/resources:/home/wiremock
    command: [ "--https-port","1002","--local-response-templating"]
    ports:
      - '80:8080'
      - '1002:1002'
  aws_sqs:
    image: roribio16/alpine-sqs
    container_name: aws_sqs
    volumes:
      - ../src/test/resources/sqs:/opt/custom
    #command: sh -c "aws --endpoint-url http://localhost:9324 sqs create-queue --queue-name hello"
    ports:
      - '9324:9324'
      - '9325:9325'
  app:
    build: ../
    depends_on:
      - "mysql"
      - "wiremock"
      - "aws_sqs"